version: '3.9'

services:
  web:
    build: .
    container_name: fastapi_app
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - backend
    expose:
      - 8000

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    restart: always
    container_name: redis_cache
    networks:
      - backend
    volumes:
      - rddata:/data

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - backend


volumes:
  pgdata:
  rddata:

networks:
  backend:
